#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
git ls-files -co | \
  ctags --tag-relative=yes -L - -f"$$.tags" \
  --languages=-javascript,sql --php-kinds=cfit
mv "$$.tags" "tags"
