#!/bin/sh

# # # # # # # # # # # # # # # # # # # # # # # #
# Setup to change screens with i3 and xrandr  #
# # # # # # # # # # # # # # # # # # # # # # # #

get_workspaces () {
	i3-msg -t get_workspaces | jq ".[] | select(.output==\"$1\").name" -r
}

workspace_toggle_output () {
	for i in $1; do
		i3-msg "[workspace=\"$i\"]" move workspace to output $2 > /dev/null 2>&1
	done
}

get_selected_output () {
	rg "set $1" ~/.config/i3/conf.d/20-workspaces.i3config | awk '{ print $3 }'
}

PRIMARY=$(get_selected_output '\$primary')
NOPRIMARY=$(get_selected_output '\$nonprimary')

xrandr --output "$PRIMARY" --noprimary
xrandr --output "$NOPRIMARY" --primary

sed -i \
	-e "5 s/$PRIMARY/$NOPRIMARY/" \
	-e "6 s/$NOPRIMARY/$PRIMARY/" \
	$HOME/.config/i3/conf.d/20-workspaces.i3config

$HOME/.bin/i3-mkconfig && i3-msg restart > /dev/null

PRIMARY_WORKSPACES=$(get_workspaces "$PRIMARY")
NOPRIMARY_WORKSPACES=$(get_workspaces "$NOPRIMARY")

workspace_toggle_output "$PRIMARY_WORKSPACES" "$NOPRIMARY"
workspace_toggle_output "$NOPRIMARY_WORKSPACES" "$PRIMARY"
