#! /bin/bash

PROGRAM=$(basename $0)

OPTS=$(getopt -o 't:p:' --long 'template:,placeholder:' -n "$PROGRAM" -- "$@")

if [ $? != 0 ] ; then echo "Error" >&2 ; exit 1 ; fi

eval set -- "$OPTS"
unset OPTS

TEMPLATE="template.html"
PLACEHOLDER="{{ content }}"

while true; do
	case "$1" in
		-t | --template ) TEMPLATE="$2"; shift 2 ;;
		-p | --placeholder ) PLACEHOLDER="$2"; shift 2 ;;
		-- ) shift; break ;;
		* ) break ;;
	esac
done

INPUT=$1

if [ ! -e "$INPUT" ]; then
	echo "Archivo $INPUT no existe :(";
	exit 1;
fi

EXP="/$PLACEHOLDER/r"
REMOVE="s/$PLACEHOLDER//g"

OUT=$(basename $INPUT .md)

sed "$EXP"<(kramdown $INPUT) $TEMPLATE | sed "$REMOVE" > $OUT.html
echo "¡$OUT.html generado! 🎉"
