#! /usr/bin/env sh

EMAIL="halivelazquez@outlook.com"

ssh-add ~/.ssh/personal

git rev-parse --is-inside-work-tree > /dev/null 2>&1

if [ $? -eq 0 ]; then
	git config --local user.name "Hali V."
	git config --local user.email $EMAIL
	git config --local user.signingKey $EMAIL
	echo "Git config added"
fi
