
[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Underline"

[font]
size = 12

[font.bold]
family = "Iosevka"
style = "Bold"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
opacity = 0.93
title = "Terminal"

[general]
import = [
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
